#!/usr/bin/env python3
"""
Pack GLB files into inline-meshes.js so they load on file:// without a server.
Run this after dropping new TRELLIS GLBs into assets/models/:
  python3 tools/pack_inline.py
"""
import base64, json, os, glob, re

MODELS_DIR = os.path.join(os.path.dirname(__file__), '..', 'assets', 'models')
OUT_FILE    = os.path.join(MODELS_DIR, 'inline-meshes.js')
STEMS       = ['volga', 'kaathi', 'meuse', 'rhine']

data = {}
for stem in STEMS:
    path = os.path.join(MODELS_DIR, f'{stem}.glb')
    if not os.path.exists(path):
        print(f'  MISSING: {path}  (skipping)')
        continue
    size = os.path.getsize(path)
    with open(path, 'rb') as f:
        b64 = base64.b64encode(f.read()).decode('ascii')
    data[stem] = b64
    print(f'  packed {stem}.glb  ({size/1024:.1f} KB → {len(b64)//1024} KB b64)')

js = '// Auto-generated by tools/pack_inline.py — DO NOT EDIT\n'
js += 'window.MMA_INLINE_GLB = ' + json.dumps(data, separators=(',', ':')) + ';\n'
with open(OUT_FILE, 'w') as f:
    f.write(js)
print(f'\nWrote {OUT_FILE}  ({len(js)//1024} KB)')
